### ISSUE TITLE
filename variables other than `$title` or `$num` (or better docs)

### ISSUE THREAD

**Issue by niklasp** [plastex/plastex#100]
I want to change my filename of the html5 renderer to 

something like

`chapter-1-$title`
`chapter-1-1-$tilte`
`chapter-2-1-$title`
in general
`$chapter-$subchapter-$title`

I can not find any documentation about the possible values for filename setting. The code does not bring me further as well. Can anyone help me? 

Or where would I be able to insert my own values, define them in python and assign a `node`-variable to it. I did not completely understand the parsing process and will have to look deeper into the code. some sequence diagrams would be great. as soon as I understood what exactly plastex is doing. I will try to do that.

I am willing to write a documentation for several scenarios. E.g. using it as a python library not with command line commands. Are there best practices? I have looked in the test folder and found some examples there. I am working at a university and we need a LaTeX to html converter and I am currently trying to get into plastex.

**Comment by kesmit13** [comment]
The class that handles filename generation is `plasTeX.Filenames.Filenames` (It's in the `plasTeX/Filenames.py` file).  It's fairly generic at that level though and doesn't know anything about the document context.  It gets instantiated in `plasTeX/Renderers/__init__.py` and stored as `self.newFilename` on the renderer object. 

The namespace used for the variables available for use in filename generation happen in the `filename` property of the `Renderer` class.  Right now, it only puts in the node ID and title, but other things could be added.

**Comment by PatrickMassot** [comment]
Fixed in  acaa91f.
