### ISSUE TITLE
A question about lineNumber

### ISSUE THREAD

**Issue by haoyun** [plastex/plastex#104]
I looked into the code, but I find it very hard to get the `lineNumber` of each generated node by the parser. What I expect is the following (XML representation), for example
```
<document bLinNum="3", eLinNum="10", id="a0000000001">
    <section ref="1", bLineNum="4", eLinNum="9", id="a0000000002">
        <plastex:arg name="title">new</plastex:arg>
        <par bLinNum="5", eLinNum="5", id="a0000000003">
            test
        </par>
        <par bLinNum="7", eLineNum="9", id="a0000000004">
            Hello, World!
        </par>
</document>
```
provided with the source file
```
1     \documentclass{article}
2     
3     \begin{document}
4     \section{new}
5     test
6     
7     Hello,%
8     World%
9     !
10    \end{document}
```

Any variant result would be fine, the goal is to keep the `lineNumber` info after parsing.

Could you give me some clues how I can manage this? Thanks a lot!

**Comment by kesmit13** [comment]
You could try to add the line number information in DOM/__init__.py:Node.toXML.  I believe it's available in self.ownerDocument.context.lineNumber.  I will say that I'm not sure how reliable that value is.  Tracking line numbers while expanding macros is quite tricky.

**Comment by PatrickMassot** [comment]
I guess there is not much more to say, unless @haoyun wants to report on trying to follow Kevin's advice, so I'll close this issue.
