### ISSUE TITLE
Confused by how to control filenames.

### ISSUE THREAD

**Issue by KelSolaar** [plastex/plastex#108]
Hi,

I would like to control the way the filenames are generated but I'm having a hard time with that.

My documents tree is as follows:

```bash
cinematic-color.tex
chapters/
├── appendix
│   ├── aces-ctl.tex
│   ├── acknowledgements.tex
│   ├── appendix.tex
│   ├── asc-cdl.tex
│   ├── camera-characterization.tex
│   ├── color-difference-encoding.tex
│   ├── colour-science-for-python.tex
│   ├── common-rgb-color-encodings.tex
│   ├── file-formats.tex
│   ├── full-and-legal-ranges.tex
│   ├── luts-and-transforms.tex
│   ├── opencolorio--ocio-.tex
│   └── software.tex
├── color-science
│   ├── about-color-science.tex
│   ├── advanced-colorimetry.tex
│   ├── basic-colorimetry.tex
│   ├── color-imaging-systems.tex
│   ├── color-science.tex
│   ├── electromagnetic-spectrum.tex
│   ├── human-visual-system.tex
│   └── representing-color.tex
├── foreword
│   ├── authorship.tex
│   ├── description.tex
│   ├── foreword.tex
│   └── on-the-web.tex
├── introduction
│   ├── a-general-model-of-color-processing.tex
│   ├── color-management-challenges.tex
│   ├── converging-approaches.tex
│   ├── how-to-read-this-document.tex
│   ├── intended-audience.tex
│   ├── introduction.tex
│   └── the-goal.tex
└── workflow
    ├── about-workflow.tex
    ├── academy-color-encoding-system-aces.tex
    ├── archives.tex
    ├── compositing.tex
    ├── critical-monitoring.tex
    ├── di-grading.tex
    ├── finishing.tex
    ├── on-set.tex
    ├── the-look.tex
    ├── visual-effects-animation-and-games.tex
    └── workflow.tex
```

And I would like to get an html file per .tex file or alike. I tried the `--filename=\$title.html` command line argument but only the first file is generated.

I'm running the very latest `python3` branch with the `HTML5` renderer.

Cheers,

Thomas

**Comment by tiarno** [comment]
Hi,
I think the doc on the file naming option is your best bet:
http://tiarno.github.io/plastex/plastex/sec-config-files.html

**Comment by PatrickMassot** [comment]
I'm trying to cleanup the issues list a little bit, so I'll close that one, since we don't have enough information to give further help. I can only comment that the new url for Tim's comment is http://plastex.github.io/plastex/plastex/sec-config-files.html. @KelSolaar  if you are still interested in this, you can reopen and I can try to help if you tell use more about what are in your tex files. Seeing the file hierarchy doesn't tell how your TeX is structured. Ideally, you should post a minimal TeX file that illustrates your problem.

**Comment by KelSolaar** [comment]
Hi @PatrickMassot,

I ended up using _tex4ht_, our tree is here for reference: https://github.com/ves-tech/cinematiccolor/tree/master/latex/chapters

**Comment by PatrickMassot** [comment]
Thanks. I think the changes I made in acaa91f (both to source code and to documention) would have been enough for your purposes, but admittedly, they come pretty late.
