### ISSUE TITLE
urls in bibliography cause errors with natbib

### ISSUE THREAD

**Issue by goska** [plastex/plastex#11]
I used a very simple document with a simple bib file (the source as fr the basic file on https://www.sharelatex.com/learn/Bibliography_management_with_natbib). I generated bbl file by running bibtex (Plastex needs bbl as input). I ran pdflatex, which produced a PDF version of the document, with references as expected. However, any attempt to generate html with Plastex processor failed, reporting error:
 ERROR: Error while expanding "ifx" in ./⁠sample-⁠with-⁠bib.bbl on line 4
   ('urlstyle' object has no attribute 'catcode')
ERROR: An error occurred while building the document object in ./⁠sample-⁠
   with-⁠bib.bbl on line 4 ('urlstyle' object has no attribute 'catcode')
I got the same error with other bibliography styles, every time I attempted to run plastex with any tex files, where their bbl files contained url key.
When I commented out the lines which caused the problem in bbl file, the conversion completed with errors (blank references ("[ ]")to the item, where url was defined, and wrong hyperlink inserted on that url in References section).

bbl file, generated with bibtex, used in the test (the lines causing the problem are commented out):

\begin{thebibliography}{3}
\providecommand{\natexlab}[1]{#1}
\providecommand{\url}[1]{\texttt{#1}}
%\expandafter\ifx\csname urlstyle\endcsname\relax
 % \providecommand{\doi}[1]{doi: #1}\else
  %\providecommand{\doi}{doi: \begingroup \urlstyle{rm}\Url}\fi

\bibitem[Einstein(1905)]{einstein}
Albert Einstein.
\newblock {Zur Elektrodynamik bewegter K{\"o}rper}. ({German}) [{On} the
  electrodynamics of moving bodies].
\newblock \emph{Annalen der Physik}, 322\penalty0 (10):\penalty0 891--921,
  1905.
\newblock \doi{http://dx.doi.org/10.1002/andp.19053221004}.

\bibitem[Goossens et~al.(1993)Goossens, Mittelbach, and
  Samarin]{latexcompanion}
Michel Goossens, Frank Mittelbach, and Alexander Samarin.
\newblock \emph{The \LaTeX\ Companion}.
\newblock Addison-Wesley, Reading, Massachusetts, 1993.

\bibitem[Knuth()]{knuthwebsite}
Donald Knuth.
\newblock Knuth: Computers and typesetting.
\newblock URL \url{http://www-cs-faculty.stanford.edu/\~{}uno/abcde.html}.

\end{thebibliography}

**Comment by tiarno** [comment]
thanks for this report--I can reproduce the problem and now I have some time to see what's going on.

**Comment by tiarno** [comment]
I think this is going to take a while. In the meantime, you could use a different style like 

    \bibliographystyle{chicago}

and the document will convert.

**Comment by goska** [comment]
Thanks - I'll try chicago style.
