### ISSUE TITLE
Issue with TeX constructor with filename arguments 

### ISSUE THREAD

**Issue by austrin** [plastex/plastex#113]
When passing a file object as the `myfile` argument to the `TeX` constructor (`def __init__(self, ownerDocument=None, myfile=None):`), that file object is added to the parse stack.

But when passing a file name instead, the string contents of that file are added to the parse stack. At some point in the past, it used to just open the file and add the file object rather than the file contents, so that these two ways behaved the same.

Only adding the file contents and not the file objects causes issues with subsequent file lookups, because the path of the original tex file is now lost (it gets `<string>` as its filename attribute) and does not get added to `TEXINPUTS` in calls to `kpsewhich`.

**Comment by PatrickMassot** [comment]
@tiarno you made that change back in 2decbb1091471b39a (line 132 of TeX.py). Would you like to comment on that? If not then I'll probably revert it.

**Comment by tiarno** [comment]
@PatrickMassot I think you're right, it was a well-intentioned mistake. Please do revert. thanks.

**Comment by PatrickMassot** [comment]
Fixed, thanks to both of you!
