### ISSUE TITLE
execution permission after pip install

### ISSUE THREAD

**Issue by ChrisMayfield** [plastex/plastex#114]
I just pip3 installed plastex-2.0, but it says "plasTeX version 1.0" when I run plastex. Did you forget to update the __version__?

https://github.com/tiarno/plastex/blob/ac3b2c6090e7871f0f966339f6d65b499ad0afaf/plasTeX/plastex#L13

Also, for some reason the installed plastex script is not executable. Do you need to chmod +x that file before packaging for PyPI?

**Comment by PatrickMassot** [comment]
I fixed `__version__` in 001261290bcda9. I'm not sure about the permission issue. It will have to wait for the next release anyway. Maybe using the entry_points mechanism is more convenient.

**Comment by PatrickMassot** [comment]
This should be fixed in the latest release.
