### ISSUE TITLE
ERROR: Could not load package "article": name 'Environment' is not defined

### ISSUE THREAD

**Issue by mennucc** [plastex/plastex#124]
dear all,
I install the latest plastex (in a python3 virtualenv, in Debian10) ; when I use plastex on LaTeX files,  that use 

> \documentclass{article}

 , the above error is displayed
bye and thanks
a.

**Comment by PatrickMassot** [comment]
Is that the full document you used? Or did you actually have a `\begin{document}` and `\end{document}`? Could you post the full python trace you see?

**Comment by mennucc** [comment]
the command is
`python3 plastex  latex_test.tex`
the file is attached,
the output is attached,
the patch that solves the problem is attached.
Bye, a.
[all.zip](https://github.com/plastex/plastex/files/3744695/all.zip)

**Comment by PatrickMassot** [comment]
Fixed, thanks!
