### ISSUE TITLE
tuple -> list

### ISSUE THREAD

**Issue by mennucc** [plastex/plastex#127]
Dear all,
by reading the documentation and the code of `Context.newenvironment`, you may think that `definition` can be of `tuple` type; but this fails, since the code tries to assign values to `definition[0]` . The attached patch fixes this. 
[1.txt](https://github.com/plastex/plastex/files/3772234/1.txt)
Bye and regards. a.

**Comment by PatrickMassot** [comment]
Thanks for reporting this weird discrepancy. I don't think this argument handling was making much sense. See ac7790b.
