### ISSUE TITLE
Version on Pypi is out of date, and not compatible with Python 3.7

### ISSUE THREAD

**Issue by pehrsoderman** [plastex/plastex#131]
The version of Plastex you get through pip3 is from jun 24th, and does not contain the fixes merged sep 15th in #118 to make Plastex compatible with Python3.7.

Would it be possible to push a current version of Plastex to Pypi?

**Comment by PatrickMassot** [comment]
Yes, this is becoming urgent. More and more people are using Python 3.7. @tiarno would you mind giving me access to the project on pypi? My login there is pmassot.

**Comment by kesmit13** [comment]
@PatrickMassot I added you to the PyPI project.

**Comment by PatrickMassot** [comment]
Thanks! Now the pressure is on me. There are still some modifications I wanted to make before the next release, but let's say I should release at the beginning of next week, even if I can't make modifications until then.

**Comment by PatrickMassot** [comment]
I published a [new version](https://pypi.org/project/plasTeX/2.1/) which should work with python 3.7 and 3.8 and incorporate recent fixes and linting. The next big thing would be to make HTML5 the default renderer and work on documentation. @kesmit13 how do you feel about that? Are you happy with this? How would you number a version doing that?

**Comment by kesmit13** [comment]
@PatrickMassot I almost think that if you are going to change something major like the default renderer, it would require a major version increment as well (to 3.0).  I do think switching to HTML5 is probably a good idea.  XHTML never really panned out as a global spec like it was originally intended.

**Comment by PatrickMassot** [comment]
Ok, I'll probably try to do that around Christmas.
