### ISSUE TITLE
problems with \if containing \newif  , and with nested \if

### ISSUE THREAD

**Issue by mennucc** [plastex/plastex#140]
dear all,

plastex gets confused when `\newif` is used inside `\if` ; see attachment test_newif_newif.tex

I attach two patches.

The first patch  warns when \if \else \fi are not properly nested (as usual `latex` does)

[pat1.txt](https://github.com/plastex/plastex/files/4142677/pat1.txt)

The second supports nested \newifs

[pat2.txt](https://github.com/plastex/plastex/files/4142678/pat2.txt)

bye. a.

ps; I attach examples

[newif.zip](https://github.com/plastex/plastex/files/4114280/newif.zip)

**Comment by mennucc** [comment]
I have found other problems: plastex is confused by nested \ifs   _e.g._ 

`\iffoo\ifbar ... \fi\fi`

this patch solves 
[pat5.txt](https://github.com/plastex/plastex/files/4155108/pat5.txt)

to see the problem, you may temporarily apply this patch 
[pat_show.txt](https://github.com/plastex/plastex/files/4155118/pat_show.txt)
 , that shows what the function `processIfContent` is doing,  and test it on this input
[simple.txt](https://github.com/plastex/plastex/files/4155134/simple.txt)

bye and tx. a.

**Comment by PatrickMassot** [comment]
I still don't understand what you want to say here, so I'll assume you fixed it in #247. Feel free to reopen with more information.
