### ISSUE TITLE
iftex

### ISSUE THREAD

**Issue by mennucc** [plastex/plastex#141]
dear all,

I implemented part of iftex.sty. I implemented the conditionals in section 3 in
[the documentation](http://ctan.mirror.garr.it/mirrors/CTAN/macros/latex/contrib/iftex/iftex.pdf)

here is the patch
[pat_if.txt](https://github.com/plastex/plastex/files/4142682/pat_if.txt)

here is a simple test file
[main.txt](https://github.com/plastex/plastex/files/4142684/main.txt)

a.

**Comment by PatrickMassot** [comment]
Thanks! Sorry about the delay.
