### ISSUE TITLE
add \ifdefined and \ifcsname

### ISSUE THREAD

**Issue by mennucc** [plastex/plastex#146]
hi

this patch adds  \ifdefined and \ifcsname
[pat_ifdef.txt](https://github.com/plastex/plastex/files/4155179/pat_ifdef.txt)

you can test it with this file
[ifdefined_ifcsname.txt](https://github.com/plastex/plastex/files/4155181/ifdefined_ifcsname.txt)

bye and tx. a.

**Comment by mennucc** [comment]
See
[this documentation](https://texfaq.org/FAQ-isdef)
for explanation of what was implemented

**Comment by PatrickMassot** [comment]
Thanks! Opening GitHub and writing tests like you did more recently make things much easier, but I'm still very grateful for your contributions and sorry about the huge delay.

**Comment by dalcde** [comment]
You can also use compare_output from helper.utils to run actual tex on the code to ensure that the benchmarks are indeed correct
