### ISSUE TITLE
Improve documentation for beginners

### ISSUE THREAD

**Issue by PatrickMassot** [plastex/plastex#164]
The documentation is currently a bit outdated, and it will become worse after #162 and #159 if we are not careful. http://plastex.github.io/plastex/tutorials/ needs some love. But the main README, http://plastex.github.io/plastex/ and http://plastex.github.io/plastex/plastex/index.html also need to be updated.

We really need to have several layers of documentation, from people who simply want to convert a simple document and don't really care about tweaking the output to what Pieter would have needed when starting the Gerby renderer. Intermediate levels include people who want to easily change some CSS or change a couple of templates.

**Comment by grunweg** [comment]
@PatrickMassot I just opened a [PR](#301) against the README, with some documentation changes that would've made things easier for me. Perhaps this helps.

**Comment by PatrickMassot** [comment]
There is now an updated getting started guide and reference manual.

**Comment by grunweg** [comment]
Wow, the new documentation looks great. Thanks a lot!
