### ISSUE TITLE
Incorrect numbering in section 0

### ISSUE THREAD

**Issue by dalcde** [plastex/plastex#172]
Consider the following file:
```latex
\documentclass{article}
\begin{document}
\subsection{Test1}
\section{Test2}
\subsection{Test3}
\end{document}
```
Compile this with the HTML5 renderer (I believe the same issue occurs with other renderers)

The section numbers we get in the rendered HTML should be
```
0.1 Test1
1 Test2
1.1 Test 3
```
However, currently, we get
```
1 Test1
1 Test2
1.1 Test3
```
Commenting out the following line fixes the issue: https://github.com/plastex/plastex/blob/master/plasTeX/__init__.py#L1644

**Comment by PatrickMassot** [comment]
Do you understand the comment "This is especially useful in document classes such as book and report which do this in the \thefigure format macro."? I'd feel better removing that line after understanding its stated purpose.

**Comment by PatrickMassot** [comment]
Also note how our life would be easier if that mysterious line had come with a unittest. That way we could see how removing it breaks something Kevin had in mind 14 years ago when he wrote https://github.com/plastex/plastex/commit/75c4b2444154fa6ddb87bbf859aca7af64567b74

**Comment by dalcde** [comment]
I do not. I agree with your sentiment which is why this is an issue and not a PR.

**Comment by PatrickMassot** [comment]
Ok, I search a bit and I see what he meant. Have a look at the pdflatex and plasTeX output with:
```latex
\documentclass{report}

\begin{document}

\begin{figure}
	\caption{My test figure}
\end{figure}

\chapter{My first chapter}
\begin{figure}
	\caption{My test figure in chapter}
\end{figure}

\end{document}
```
If you remove that mysterious line then you won't get the same output. Search for thefigure in https://www.tug.org/svn/texlive/trunk/Master/texmf-dist/tex/latex/base/report.cls.

But it's hard to believe there isn't a better solution.
