### ISSUE TITLE
_ is broken

### ISSUE THREAD

**Issue by mennucc** [plastex/plastex#192]
hi

with todays plasTeX 63d7a0d this simple LaTeX fails:

> \documentclass{article}
> \begin{document}
>     ${\mathcal A}=\bigcup_{i\in I} A_i$
> \end{document}

output  is attached
[typescript.txt](https://github.com/plastex/plastex/files/4518312/typescript.txt)

**Comment by mennucc** [comment]
I identified the culprit using bisect as follows

> export PYTHONPATH=`pwd`
>   git bisect start
>   git bisect  good 2b0791bf82b499f8c1f7819b5728db2f2c30a16a
>   git bisect bad  63d7a0d 
>   git bisect run python3 plasTeX/plastex plastex_test.tex 

and the culprit is  commit fbb79a55334d07746b21d1f0c64cf54d1fd731f1

**Comment by mennucc** [comment]
this fix works
[patch.txt](https://github.com/plastex/plastex/files/4518412/patch.txt)

**Comment by dalcde** [comment]
The issue is actually with the `\mathcal`, not the underscore.
