### ISSUE TITLE
Add option to disable loading TeX packages

### ISSUE THREAD

**Issue by dalcde** [plastex/plastex#200]
This would be very helpful since these fail most of the time anyway. There ought to be a way to manually force loading a particular package (possibly in the TeX source) in case some can actually be parsed (most likely written by the user themselves).

In such situations, if there is no python implementation, the package is simply not loaded, and a warning is produced. This feature would be especially useful when users use some large preamble that is included by all their documents, and many of the packages might not actually be used in the particular document they try to compile.

**Comment by PatrickMassot** [comment]
I agree this would be useful. I guess the list of packages to try to load anyway can be a plasTeX option.

**Comment by PatrickMassot** [comment]
Fixed in e23616a11f20989072997f3049f8a8a87f266224
