### ISSUE TITLE
Config Manager

### ISSUE THREAD

**Issue by PatrickMassot** [plastex/plastex#201]
@dalcde I just reverted your commit 99fc05c since it completely broke config file reading. 

There is a recurring theme here. The `ConfigManager` subpackage is cursed:
* This is 3000 lines of python which have *nothing* to do with either TeX or DOM.
* It has been a major pain when switching to python3.
* I think it caused most of the `mypy` PR pain.
* it relies a lot on side effects (as illustrated by your breaking change)
* It has things like [GenericParser](https://github.com/plastex/plastex/blob/525a41ed299456db1c7f095ce3f75555dc196d3d/plasTeX/ConfigManager/Generic.py#L30) which is a class with no parent and no `__init__`  whose methods [refer](https://github.com/plastex/plastex/blob/525a41ed299456db1c7f095ce3f75555dc196d3d/plasTeX/ConfigManager/Generic.py#L60) to things like `self.optional`, hoping that subclasses will define it.

My hope is no alternative existed 20 years ago when this was written, but maybe we could get rid of it now. I say: let's investigate.

**Comment by dalcde** [comment]
On Mon, May 04, 2020 at 01:17:07PM -0700, Patrick Massot wrote:
>@dalcde I just reverted your commit 99fc05c since it completely broke config file reading.
>
>There is a recurring theme here. The `ConfigManager` subpackage is cursed:
>* This is 3000 lines of python which have *nothing* to do with either TeX or DOM.
>* It has been a major pain when switching to python3.
>* I think it caused most of the `mypy` PR pain.
>* it relies a lot on side effects (as illustrated by your breaking change)
>* It has things like [GenericParser](https://github.com/plastex/plastex/blob/525a41ed299456db1c7f095ce3f75555dc196d3d/plasTeX/ConfigManager/Generic.py#L30) which is a class with no parent and no `__init__`  whose methods [refer](https://github.com/plastex/plastex/blob/525a41ed299456db1c7f095ce3f75555dc196d3d/plasTeX/ConfigManager/Generic.py#L60) to things like `self.optional`, hoping that subclasses will define it.
>
>My hope is no alternative existed 20 years ago when this was written, but maybe we could get rid of it now. I say: let's investigate.

I would be more than happy to get rid of this piece of code.

**Comment by dalcde** [comment]
I am unable to find a package that quite does what `ConfigManager` allows, but we can get rid of a lot of code by letting `argparse` do the command line parsing.

**Comment by dalcde** [comment]
Currently one can specify the initial values of counters by `--counters [ countera 1 counterb 3 ]`, which is not very typical command line behaviour. Would you object to changing this to `--counter countera=1 --counter counterb=13`?

**Comment by PatrickMassot** [comment]
I also couldn't find an existing package doing everything ConfigManager does. I like [docopt](http://docopt.org/)'s idea but being untyped makes it unusable without duplicating everything, as explained in https://github.com/docopt/docopt#data-validation. We could fix this but this would be a totally different project (using python's type annotation syntax in docopt would be really nice). 

Many existing libraries like [click](https://click.palletsprojects.com/en/7.x/) or [fire](https://github.com/google/python-fire) focus on having a lot of subcommands with a handful of options for each command. This is exactly the opposite of what we need. There is also the issue that none of these project handle merging configuration from command line, config files and default values, but this seems very easy to arrange. 

If I had time I would work on a fork of docopt implementing type annotations in the help string and merging sources. But I don't have time and I see you started something else anyway. Maybe it's a good idea to mostly keep the interface and simply fix the implementation, relying as much as possible on existing stuff. If you go that way, it would be nice to really split off this module. It could be hosted by the plastex organization on GitHub but packaged separately (with a dependency from plastex to the config manager but not the other way around).

**Comment by PatrickMassot** [comment]
> Currently one can specify the initial values of counters by `--counters [ countera 1 counterb 3 ]`, which is not very typical command line behaviour. Would you object to changing this to `--counter countera=1 --counter counterb=13`?

I don't mind. I'm actually surprised shells can parse that. And plasTeX 3.0 will be breaking of lot of things anyway, simply by changing the default renderer.

**Comment by dalcde** [comment]
I think I'm happy with the way it is handled in #206 ; see https://github.com/plastex/plastex/blob/c4c8d33c1336fba64744de7455e8e042fbf13c65/plasTeX/ConfigManager/__init__.py for the code since the commit diff is unhelpful. It's a tiny wrapper around argparse, which can be replaced with docopt if you prefer, but I'd rather not have an external dependency.

I'm pretty confident the resulting object will be less than 200 lines. If so, I don't think it is necessary to split it off to a different package.

**Comment by dalcde** [comment]
One possible loss of functionality: In my understanding, currently, the ConfigManager supports interpolation, which I believe is similar to/the same as what is described here: https://docs.python.org/3/library/configparser.html#interpolation-of-values . With the new code, interpolation would still work within each ini file read, since we are using ConfigParser and ConfigParser supports it, but will not work across multiple config sources.

**Comment by PatrickMassot** [comment]
Did you test that interpolation currently works across sources?

**Comment by dalcde** [comment]
Yes it does.

**Comment by dalcde** [comment]
I discovered a place that relies on there being a global config --- `Logging.py`. It's not clear to me if we really need a custom logging framework.
