### ISSUE TITLE
A plastex tex package

### ISSUE THREAD

**Issue by dalcde** [plastex/plastex#205]
It might be helpful to have a tex package for use with plastex. Currently i have such a package that I put in cwd that defines the following:
 * A `useimager` environment that causes the content within to be rendered using the imager
 * the `\ifplastex` command
 * A version of `\texorpdfstring` that has a third option for what to display in html. This functionality can be replicated by `\ifplastex` but is much more convenient.

We can also add the following:
 * Add an optional argument to `\usepackage` to force parsing/non-parsing of tex packages a la #200 
 * We can similarly modify `\renewcommand` for the purposes of #90

**Comment by PatrickMassot** [comment]
I'm not sure I understand the proposal. Some of your goals seem to be directed towards plastex and some towards pdflatex. If you want the package to be available to pdflatex, where do you want to put that package? In plasTeX? At CTAN? In TeXLive?

**Comment by dalcde** [comment]
It is used for documents that are intended to be compiled with both
pdflatex and plastex. I have no opinions on where it ends up.
