### ISSUE TITLE
Remove ZPT renderer for plasTeX 3.0?

### ISSUE THREAD

**Issue by dalcde** [plastex/plastex#208]
As per the documentation,
>NOTE: This module isn't really needed any more.  The PageTempate renderer does everything that this module did and more.  This is just here for backwards compatibility.

The renderer merely re-exports `PageTemplate`

**Comment by PatrickMassot** [comment]
What would we gain here?

**Comment by dalcde** [comment]
It removes deprecated code (albeit only a few lines). ZPT is never used
directly anyway since it doesn't have any templates. So the only change
people have to make is to replace inheriting ZPT with inheriting
PageTemplate.

**Comment by PatrickMassot** [comment]
Fixed in bd5f4113db39d7f5b367b55dd6ef16cb562c3618
