### ISSUE TITLE
Confusing behaviour of --counter option

### ISSUE THREAD

**Issue by dalcde** [plastex/plastex#209]
Currently, if we set
```
[counters]
section = n
```
in the configuration, it actually sets the counter to `n - 1`, so that whenever it is next invoked, the value of the counter is incremented to `n`. This is inconsistent with latex and counterintuitive once you are aware of how to set counters in TeX.

**Comment by PatrickMassot** [comment]
I'd need to see a concrete patch here. The current code has the expected behavior: from `test.tex` containing
```latex
\documentclass{article}

\begin{document}
\section{Test section}
\end{document}
```
you can run `plastex --counter [section 3] test.tex` and get a document which starts with section `3. Test section`.

**Comment by dalcde** [comment]
Naively, I would expect the behaviour to be equivalent to
```latex
\documentclass{article}

\setcounter{section}{3}
\begin{document}
\section{Test section}
\end{document}
```
which would produce `4. Test section.`

Alternatively, if the code is
```latex
\documentclass{article}

\begin{document}
\thesection
\end{document}
```
and you run with `plastex --counter [section 3] test.tex` you get `2` instead of `3`. 

The patch would be to remove the `-1` at https://github.com/plastex/plastex/blob/master/plasTeX/Base/LaTeX/Document.py#L32

**Comment by PatrickMassot** [comment]
I think the semantic of plasTeX is the sensible one, and it's well documented. The TeX version is simply something else. If you want to use `\setcounter` you can do it from the TeX file. I don't see any reason to break backward compatibility here.

**Comment by dalcde** [comment]
I disagree that it is well-documented. The documentation merely says the
command "sets the counter to the value", which one would ordinarily
expect to be equivalent to what "setting the counter" does in TeX.

(I also think what TeX does is sensible once from a logical point of
view. One would expect \setcounter{section}{3}\thesection to return 3.)

At the very least, we should correct the documentation.

**Comment by PatrickMassot** [comment]
Of course `\setcounter{section}{3}\thesection` does the sensible thing, that's why I wrote those are two different things. You can update the documentation if you want (as long as you describe what the option does instead of writing you think this is wrong).

**Comment by dalcde** [comment]
I will also expect `--counter section 3` and `\thesection` to return 3,
but let's leave the discussion here.

I will say that the behaviour differs from \setcounter without passing
on any value judgement. This will be part of the ConfigManager patch
because I'll be rewriting a lot of config documentation.
