### ISSUE TITLE
Add an attribute to TeXDocument that store package options

### ISSUE THREAD

**Issue by dalcde** [plastex/plastex#216]
Currently, some packages (e.g. `listings`) store the package options in some global variable, which would break if plasTeX is used to compile multiple files with different options. Others (e.g. todonotes) use some ad hoc attribute in `TeXDocument`. It would be nice to have some dict designed to store this information for consistency.

**Comment by PatrickMassot** [comment]
Same comment as in #219: https://github.com/plastex/plastex/blob/master/plasTeX/PackageResource.py is meant to handle this. I'm open to improvements here of course.

**Comment by dalcde** [comment]
I think I'm looking for something much simpler --- simply a dict for
each package. The use case of PackageResource seems different.

**Comment by PatrickMassot** [comment]
I noticed there is already https://github.com/plastex/plastex/blob/master/plasTeX/Context.py#L180-L181 which is used to store package options in https://github.com/plastex/plastex/blob/master/plasTeX/TeX.py#L207. Shouldn't we use that?

**Comment by dalcde** [comment]
That's supposed to store the "raw" options specified in the \usepackage
command. It might be helpful to be able to store "processed" ones as
well.

**Comment by PatrickMassot** [comment]
It seems to me that the current recommendation is to store those things in the document `userdata` dictionary. Arguably, this `userdata` thing is a bit messy. In particular there is no rule saying that a package should store things only under a path starting with its own name (recall `userdata` is not a regular dictionary, it is a `DOMUserData`, defined in `DOM/__init__.py`, so there is a notion of path).

One question is: are we talking about data that should be attached to a document or to a context? Loaded packages are logically part of the context, but I don't see any current example where we couldn't attach the data to the document. 

I fear that creating a new dictionary besides `document.userdata` simply add complexity and more breaking of the rule "There should be one-- and preferably only one --obvious way to do it."

**Comment by dalcde** [comment]
On Sat, May 23, 2020 at 04:09:14AM -0700, Patrick Massot wrote:
>One question is: are we talking about data that should be attached to a
>document or to a context? Loaded packages are logically part of the
>context, but I don't see any current example where we couldn't attach
>the data to the document.

I don't think there is a difference in practice. Packages must be loaded
in the preamble.

**Comment by PatrickMassot** [comment]
Yes, this is what I think. So there doesn't seem to be any serious obstruction to putting things in `document.userdata`.

**Comment by PatrickMassot** [comment]
I fixed both the examples you mentioned.
