### ISSUE TITLE
Load HTML5 template based on TeX Package

### ISSUE THREAD

**Issue by dalcde** [plastex/plastex#219]
Some packages modify the way certain commands behave or are displayed. For example, imakeidx lets us configure the way the index page is displayed based on options set at \makeindex. It would be helpful for there to be a template that is loaded iff a package is loaded, and can potentially overwrite existing tempaltes.

**Comment by PatrickMassot** [comment]
https://github.com/plastex/plastex/blob/master/plasTeX/PackageResource.py and https://github.com/plastex/plastex/blob/edce060321acd1f5f4e2fa263e0dc3eb02808ae0/plasTeX/Renderers/HTML5/__init__.py#L67-L74 are meant to allow this kind of things.

**Comment by dalcde** [comment]
It seems like adding a PackageResource to a package would require
modifying the python package file, which may be undesirable if users
want to add their own. I'm thinking of something simpler, e.g. having a
(sub)directory that contains templates to be loaded for each package,
with the filename corresponding to the package name.

**Comment by dalcde** [comment]
This might mean what we have to do is to come up with an alternative way
to load PackageResource's
