### ISSUE TITLE
seeking advice re: updating project done with PlasTeX version 0.93

### ISSUE THREAD

**Issue by nealeyoung** [plastex/plastex#220]
If this is not the appropriate forum to post this question, please let me know where I should ask it, thanks.

A while back I used PlasTeX version 0.93 to build a wordpress site about algorithms, including proofs about algorithms.  To do that, I augmented PlasTeX by adding a variety of custom templates and some additional code, to support new latex macros for a variety of things.  These included:
- boxes that are by default closed, but can be open to see the contents (e.g. for proofs), 
- an environment for writing algorithms, 
- support for equation numbering and the \ref mechanism (so I can refer to latex labels and have the correct numbers appear in the final html document), 
- inline images, 
- math expressions via mathjax,
- custom page formatting, to support "page" structures in HTML
and so on.  I believe I used the Zope templating system that was included with PlasTeX 0.93.

You can see the results at [https://algnotes.info](https://algnotes.info) .

I'm considering updating this project and perhaps doing another similar project.  I'm looking for advice about the best way to proceed.  Is any of the functionality that I added now available (as a built-in or via an easily addable library of some sort) in PlasTeX 2.0?  (I notice that some of the GitHub contributors seem to have done some similar extensions to PlasTeX.  Are those available or easily integrable?)

The documentation of PlasTeX 0.93 did not cover how to do the kind of customizations I wanted to do, so I had to figure it out by looking at the code.  Is it substantially better now?

Getting PlasTeX 0.93 to do all these things took a lot of work.  How much work will it be in PlasTeX 2.0?  

Should I wait for PlasTeX 3.0?  Should I consider some other LaTeX-to-HTML translator?  (A few years ago I couldn't find another one that could be extended to do the things I wanted.)

Etc.

Thanks for any advice you can give.

**Comment by PatrickMassot** [comment]
We don't have a better place to discuss such things, although it's true that GitHub issues are not really the right tool.

Everything you describe is totally in scope for plasTeX, especially the 3.0 version we are currently working on, as you probably saw by browsing the currently open issues (starting from the most recent ones). Indeed we have most of these appearing either in current plasTeX or in custom forks. We hope to make all this much easier and better documented in the near future. 

> boxes that are by default closed, but can be open to see the contents (e.g. for proofs),

I have this, and this will be made easier soon.
>  an environment for writing algorithms,

I need more details here (in a dedicated issue). Do you mean having some implementation of [listings](https://ctan.org/pkg/listings) or something more exotic?

>   support for equation numbering and the \ref mechanism (so I can refer to latex labels and have the correct numbers appear in the final html document),

I don't understand how this differs from what has always existed.

>  inline images,

Same as above, this already exists.

> math expressions via mathjax,

This is already done by default in the HTML5 renderer (that will become the default renderer in plasTeX 3.0 but you can already use it).

>  custom page formatting, to support "page" structures in HTML

I don't understand that one.

> I believe I used the Zope templating system that was included with PlasTeX 0.93.

This is still supported, although it's arguably a bad idea, unless you are already using a very similar template engine for other purposes and don't want to have to switch.

**Comment by nealeyoung** [comment]
The details of the "page structures" I was referring to aren't important.. but you could check the site to see what I mean if you want.  The point is that to implement that feature I had to add some non-trivial macros that required both new templates and new python code.  The real question I guess is whether the system is now (or will be soon) well-documented enough and somehow organized so as to make adding and maintaining such features relatively easy.  

Overall, I had the feeling that as of version 0.93 at least with PlasTeX I could achieve some really nice results, but doing so required a  large amount of work both upfront and to a lesser extent in maintenance.   I was lured into it as a "hacking" experience, one that I enjoyed, but I suspected that, from a more rational cost/benefit perspective, the work it took wasn't justified just by the final product.  So I'm wondering whether it's gotten much easier to use.  (Looking over the current documentation, it's not at all clear.)  If not I probably can't justify the work it would take me to upgrade my previous project or do a new one.

**Comment by PatrickMassot** [comment]
It's hard to make promises in such a project where everybody is doing this as a hobby (or structured procrastination), but you can see from the project activity that we are really working on this. I certainly hope that plasTeX 3.0 will be released before summer, and you'll be able to play with it before the release. I'm currently working on #167, which is the main thing that you'll need.

**Comment by dalcde** [comment]
Some version of it is working, definitely, since I'm using it. I'm not sure about the documentation part and I've forgotten about most of my setup. I remember it being reasonably easy to use, but I also had some knowledge of plastex internals.

**Comment by PatrickMassot** [comment]
I does work, and is somewhat documented. You can search for plugin in the manual. You can also have a look at a real world example at https://github.com/PatrickMassot/leanblueprint/. If you tell me what you want to do with a plugin then I can try to improve the documentation.

**Comment by PatrickMassot** [comment]
I added documentation about plugins in the reference manual.
