### ISSUE TITLE
broken  e1c6355

### ISSUE THREAD

**Issue by mennucc** [plastex/plastex#230]
dear all,

the current GIT version e1c6355 is broken, it does not work even on the simplest input file, returning

> $ plastex  example.tex 
> Traceback (most recent call last):
>   File "/home/a/src/plastex_virtualenv/bin/plastex", line 6, in <module>
>     import plasTeX
>   File "/home/asrc/plastex_virtualenv/lib/python3.6/site-packages/plasTeX/__init__.py", line 6, in <module>
>     from plasTeX import Logging, encoding
>   File "/home/a/src/plastex_virtualenv/lib/python3.6/site-packages/plasTeX/Logging.py", line 141, in <module>
>     root = Logger()
>   File "/home/a/src/plastex_virtualenv/lib/python3.6/site-packages/plasTeX/Logging.py", line 32, in __init__
>     level = locals().get(defaultConfig()['logging']['logging'].get(name))
>   File "/home/a/src/plastex_virtualenv/lib/python3.6/site-packages/plasTeX/Config.py", line 14, in defaultConfig
>     general = config.addSection('general')
> AttributeError: 'ConfigManager' object has no attribute 'addSection'
>

regards. a.

**Comment by dalcde** [comment]
Does this happen with a fresh installation of plastex? I think you are
somehow importing the wrong version of ConfigManager.

**Comment by mennucc** [comment]
I am quite puzzled. 

Yesterday I was careful to download a fresh copy of plastex from GIT, and then I installed it in a freshly created virtualenv, before posting this bug. As you see from the traceback, indeed , all code files were in that virtualenv. But today I tried once again, and I cannot reproduce the error. 

Today I tried again, same steps but in a different directory: download a fresh copy of plastex from GIT, and then I installed it in a freshly created virtualenv: this works fine.  (!)

I tried to `diff` the two virtualenvs... there is no outstanding difference, that is, the compiled `.pyc` are different, but all `.py` files are equal. 

Still, one works, one does not.

I am closing this bug, altough I would like to understand what went wrong

BTW : also used `pip3 list` and

# find /usr/ .local -iname '*plastex*'

to check that no cruft was left around outside the virtualenvs : nothing.
