### ISSUE TITLE
WARNING: No Python version of etoolbox.sty was found

### ISSUE THREAD

**Issue by mdk73** [plastex/plastex#238]
I get a warning (and connected additional warnings) when I try to load the package etoolbox:

```latex
\documentclass[a4paper,10pt,fleqn, twoside]{book}
\setlength{\textwidth}{17cm}
\setlength{\textheight}{28cm}
\setlength{\evensidemargin}{0cm}

\usepackage{etoolbox} % for magic row numbers

\begin{document}
Test.
\end{document}
```

```
WARNING: No Python version of etoolbox.sty was found
 ( C:/Users/.../AppData/Local/Programs/MiKTeX/tex/latex/etoolbox/etoolbo
   x.sty
..
WARNING: unrecognized command/environment: PackageError
WARNING: unrecognized command/environment: MessageBreak
WARNING: unrecognized command/environment: aftergroup
```

Complete console output:
```
WARNING: Cannot find unidecode lib. Expect issues with index sorting
 ( C:\ProgramData\Anaconda3\lib\site-packages\plasTeX\Packages\book.py )..
WARNING: No Python version of etoolbox.sty was found
 ( C:/Users/.../AppData/Local/Programs/MiKTeX/tex/latex/etoolbox/etoolbo
   x.sty
..
WARNING: unrecognized command/environment: PackageError
WARNING: unrecognized command/environment: MessageBreak
WARNING: unrecognized command/environment: aftergroup
 )..
INFO: Directing output files to directory: ..\html.
INFO: Importing templates from C:\ProgramData\Anaconda3\lib\site-
   packages\plasTeX\Renderers\PageTemplate
INFO: Importing templates from C:\ProgramData\Anaconda3\lib\site-
   packages\plasTeX\Renderers\XHTML
INFO: Importing templates from C:\ProgramData\Anaconda3\lib\site-
   packages\plasTeX\Renderers\XHTML\Themes\default
INFO: Using the imager "dvipng".
 [ index.html ]
```

**Comment by PatrickMassot** [comment]
I don't understand why you opened this issue. Do you mean you intend to work on implementing etoolbox in python? Or do you intend to open an issue for each of the thousands LaTeX packages that have no python version?

**Comment by mdk73** [comment]
>Do you use this issue to announce you intend to work on implementing etoolbox in python?

I wish I could, but that would be much above my skill level, sure for LaTex, and probably also on the python side.
So no, I am not going to implement this package.

>As the above message says, plasTeX tried to parse the TeX implementation etoolbox.sty. But this will work only for simple packages, and etoolbox is very far away from this category. See the relevant part of the documentation.

With your explanation I understand this warning better. So plasTex tried to parse the LaTex package, and was not able to deal with the following commands from command/environment: 

- PackageError
- MessageBreak
- aftergroup

And as there is no etoolbox.py solving these issues, I will have to find my way around etoolbox using `ifplastex` and conditional importing.
Is that correct?

**Comment by PatrickMassot** [comment]
Yes. In my experience the most efficient trick is to have separate preambles. When using plasTeX I typically have three files: `paper.tex`, `web.tex` and `content.tex`. The first two files both contain `\input{content}`which contain all the actual content. But they have different `\usepackage` and macro definitions (you can still put common macros in `content.tex`, or in a fourth file).

A lot of complicated LaTeX packages actually don't make any sense when the document is not intended for print, or they can easily be replaced by CSS on the web. The case of `etoolbox` is very special of course, I cannot say anything without knowing more about your use case.
