### ISSUE TITLE
PNGs broken in XHTML themes

### ISSUE THREAD

**Issue by petef4** [plastex/plastex#245]
The PNGs in XHTML themes are broken and cannot be viewed. 

I looked at a binary dump of one of them default/icons/overlay.png. Compared with the file in plasTeX 1.0.0 it has an extra byte at index 4,, 0x0d inserted before 0x0a. So it looks as if unix2dos or equivalent has mistakenly been run on it, 

A fix should be possible by reverting to an earlier version of the 10 PNG files.

The GIF files seem okay.

```
find . -name \*.png | xargs -rL 1 identify
identify: improper image header `./Renderers/XHTML/Themes/default/icons/missing.png' @ error/png.c/ReadPNGImage/3647.
identify: improper image header `./Renderers/XHTML/Themes/default/icons/overlay.png' @ error/png.c/ReadPNGImage/3647.
identify: improper image header `./Renderers/XHTML/Themes/python/icons/blank.png' @ error/png.c/ReadPNGImage/3647.
identify: improper image header `./Renderers/XHTML/Themes/python/icons/contents.png' @ error/png.c/ReadPNGImage/3647.
identify: improper image header `./Renderers/XHTML/Themes/python/icons/index.png' @ error/png.c/ReadPNGImage/3647.
identify: improper image header `./Renderers/XHTML/Themes/python/icons/modules.png' @ error/png.c/ReadPNGImage/3647.
identify: improper image header `./Renderers/XHTML/Themes/python/icons/next.png' @ error/png.c/ReadPNGImage/3647.
identify: improper image header `./Renderers/XHTML/Themes/python/icons/previous.png' @ error/png.c/ReadPNGImage/3647.
identify: improper image header `./Renderers/XHTML/Themes/python/icons/pyfav.png' @ error/png.c/ReadPNGImage/3647.
identify: improper image header `./Renderers/XHTML/Themes/python/icons/up.png' @ error/png.c/ReadPNGImage/3647.
```

Running the same command in plasTeX 1.0.0 correctly lists the attributes of the image files.

**Comment by PatrickMassot** [comment]
Sorry about the delay (and the broken icons). I'd be curious to know why anyone still wants to use the XHTML renderer. Are you trying to recompile a very old project?

**Comment by petef4** [comment]
We deliver our documentation as both PDF and XHTML from an embedded web server. That was set up 12 years ago.

Are there plans to release a new version of plasTeX to PyPI? That is where our build pulls it from. If that is not soon I will make a work around.
