### ISSUE TITLE
mathtools package

### ISSUE THREAD

**Issue by kno10** [plastex/plastex#249]
The mathtools package seems to cause issues with plastex.
It would be good if it at least produced a comprehensible error message, not just "TypeError: ord() expected a character, but string of length 8 found"

See, e.g., https://github.com/coursebuilder-ncl/makecourse/issues/65

**Comment by PatrickMassot** [comment]
It does produce a comprehensible warning: 
```
WARNING: No Python version of mathtools.sty was found
WARNING: Will now try to load a LaTeX implementation of mathtools.sty
```
As explained in the documentation, plasTeX tries to load LaTeX versions of unknown packages, but this will succeed only for the simplest packages. Basically it will work if you have a homemade package defining a couple of new commands and environments. But mathtools is not in this category. Actually it is mostly irrelevant from a plasTeX point of view but you'll get unexpected results from mathjax not supporting it.
Anyway, I added a warning in 9a5cfb0
