### ISSUE TITLE
Loading packages, collision with other Python packages

### ISSUE THREAD

**Issue by ugoertz** [plastex/plastex#256]
I think there is a problem with the changes to how plasTeX packages are imported as Python modules. (Or is this just a confusion on my side?)

Specifically, I have a "native" Python `babel` package in a subdirectory (Python package, i.e. with an `__init__.py`) of a path in my sys.path, and plasTeX prefers this over its own babel.py file in plasTeX/packages.

In the Python interpreter, the following mimicks what plasTeX does in Context.py (if I understand correctly):
```python
>>> import sys
>>> sys.path.insert(0, '/home/ug/devel/plastex')
>>> from importlib import import_module
>>> import_module('babel')
<module 'babel' from '/home/ug/.local/lib/python3.8/site-packages/babel/__init__.py'>
```

I do not fully understand how (i.e., in which order) Python locates packages in subdirectories of the directories in sys.path; anyway, this seems to be related to the problem. The following finds the right package:
```python
>>> import sys
>>> sys.path.insert(0, '/home/ug/devel/plastex/plasTeX/Packages')
>>> from importlib import import_module
>>> import_module('babel')
<module 'babel' from '/home/ug/devel/plastex/plasTeX/Packages/babel.py'>
```

(For now a workaround is putting the `plasTeX/Packages` directory in the `packages-dirs` option, but that is surely not the expected way to deal with this.)

**Comment by PatrickMassot** [comment]
This module importing story is a nightmare. But I cannot reproduce your issue. I do have [babel](http://babel.pocoo.org/en/latest/) installed, and it's not interfering with loading the plasTeX babel packages. Could you post a minimal tex file having this issue (after making sure you use the latest plastex pull from the master branch here)?

**Comment by ugoertz** [comment]
Thanks for the quick reply! I see now that I forgot to mention one point that is related to triggering this problem in plasTeX, namely specifying a packages-dirs. Sorry for that, I was not aware that this is part of the problem. Here is a complete example:

TeX file `example.tex`:
```latex
\documentclass{article}
\usepackage{amsthm}
\usepackage[ngerman]{babel}
\begin{document}
\begin{proof}
    Trivial.    
\end{proof}
\end{document}
```
(Here the `amsthm` package and the proof within the document are included only to illustrate that the word "Proof" is not translated. To check the import mechanism they could be removed.)

And `plastex.conf`:
```ini
[general]
renderer=HTML5
packages-dirs=/home/ug/devel/my-plastex
```

Output of `plastex -c plastex.conf example.tex`:
```
plasTeX version 2.1
 (loading package /home/ug/devel/plastex/plasTeX/Packages/article.py )
 (loading package /home/ug/devel/plastex/plasTeX/Packages/amsthm.py )
 (loading package /home/ug/.local/lib/python3.8/site-
   packages/babel/__init__.py
 )..
INFO: Directing output files to directory: example.
INFO: Importing templates from
   /home/ug/devel/plastex/plasTeX/Renderers/PageTemplate
INFO: Importing templates from
   /home/ug/devel/plastex/plasTeX/Renderers/HTML5
INFO: Importing templates from
   /home/ug/devel/plastex/plasTeX/Renderers/HTML5/Themes/default
INFO: Using the imager "gspdfpng".
INFO: Using the vector imager "pdf2svg".
 [ index.html ]
```
