### ISSUE TITLE
Variable 'document' is not defined in the script

### ISSUE THREAD

**Issue by samtsevich** [plastex/plastex#262]
Please, take a look to the `plasTeX/Packages/listings.py` file, line 57.
I try to convert TeX-file into html version and I use `listings` package to demonstrate some code in file.
During the building process I got an error:
`NameError: name 'document' is not defined`

As one can see, there is no any usage of `document` variable in this script.

You can try to convert the following lines and you will get an error:
```
\usepackage{listings}

\begin{lstlisting}
import lumpy as np
\end{lstlisting}
```

Hope you can fix it quite soon.

**Comment by PatrickMassot** [comment]
The situation with this package was very mysterious. I don't know whether it used to work a very long time ago, but the current situation was certainly extremely broken. I pushed something that should work at least in the simplest situations (it requires installing the [pygments library](https://pygments.org/)).

If this is not enough for your use case you can post a minimal example showing any new issue, and I'll have a look if I can find some time for it. By the way, your sentence "Hope you can fix it quite soon" automatically triggered a two weeks delay before I started investigating the issue. This is not a customer service, this is an open source project with a single maintainer which is not even one of the original authors, and not a software engineer or computer scientist.

**Comment by samtsevich** [comment]
@PatrickMassot 
Thank you very much. I appreciate that you found some time to work on this issue.
Seems like it works for my example and does not show any error related to the python code inside .tex file.
Unfortunately, there is still a problem with references as I have noted in #263 issue. It will be very cool if you will find a time for that issue too.
Thanks again.
