### ISSUE TITLE
eqnarray and align and \[\]

### ISSUE THREAD

**Issue by mennucc** [plastex/plastex#269]
dear Patrick
there are some issues with eqnarray and align: to compile for HTML5 one has to add `\[\]` around them , while in standard LaTeX and for XHTML you don't.

You can compile this
[align_xhtml.txt](https://github.com/plastex/plastex/files/8102708/align_xhtml.txt)
using `plastex --renderer XHTML -d align_xhtml align_xhtml.txt` , and also with standard `pdflatex` ; but if you compile it to html5, then the result will be incorrect, since mathjax delimiters will not be there; you  have to add `\[\]` , as in this example 
[align_html5.txt](https://github.com/plastex/plastex/files/8102726/align_html5.txt)

bye a.

**Comment by mennucc** [comment]
(there is another issue, that you know of: numbering of equations does not work; I will look into it sometimes)

**Comment by PatrickMassot** [comment]
This has nothing to do with `\[\]` which kind of accidentally fixed the issue. It's the same issue as in #143 which wasn't propagated to these environments. [8dffc02](https://github.com/plastex/plastex/commit/8dffc0281fe7b0a0ba6cc5498f597d0492f483cb) hopefully improves the situation.
