### ISSUE TITLE
sys.path too large

### ISSUE THREAD

**Issue by mennucc** [plastex/plastex#270]
Dear Patrick,

I use plasTeX inside my project; the code creates many instances of TeX objects, to compile latex fragments; but each time paths are added to sys.path, and at a certain point the Apache server  starts misbehaving. I have created a patch for this.

[0090-do-not-reinsert-paths-in-syspath.txt](https://github.com/plastex/plastex/files/8103843/0090-do-not-reinsert-paths-in-syspath.txt)

Regards
a.

**Comment by PatrickMassot** [comment]
Thanks Andrea. I'm sorry that using plasTeX as a library compiling a lot of fragments is very poorly tested.
