### ISSUE TITLE
log, filter, OSError

### ISSUE THREAD

**Issue by mennucc** [plastex/plastex#272]
dear Patrick,

in line 193 of TeX.py there is

```
        try:
            path = self.kpsewhich(file)
        except OSError as msg:
            log.warning(msg)
            return False
```
so it may happen that an instance of OSError may be sent to the logging; but the dotfilter expects strings, so it crashes in that case (it happened to me); so long ago i prepared this patch.

[0050-logging-do-not-filter-non-str.txt](https://github.com/plastex/plastex/files/8123045/0050-logging-do-not-filter-non-str.txt)

I have used it for a year in my code, it works fine.

a.

**Comment by PatrickMassot** [comment]
Merged, thanks!
