### ISSUE TITLE
Line numbering inconsistency?

### ISSUE THREAD

**Issue by kno10** [plastex/plastex#274]
The current code appears to sometimes overcount the line numbers.
Right now, I have an error reported as
ERROR: Error while expanding "only" in text.tex on line 197 (string index out of range)
but the file only has 193 lines.
I believe this may be due to verbatim sections.
Sorry, I don't have a MWE yet.

**Comment by PatrickMassot** [comment]
Thanks for trying to help but, as you know, there is nothing I can do without an example.

**Comment by kno10** [comment]
It appears that `\makeatletter` and `\makeatother` cause line numbers to be off:
```
\documentclass{article}
\makeatletter
\makeatother

\newcommand{}}} % Intentional error for the MWE
\begin{document}\end{document}
```
Error is reported to be
```
ERROR: Error while parsing argument "name" of "newcommand"
ERROR: Error while expanding "newcommand" in ./mwe3.tex on line 7 (pop from
   empty list)
```
