### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'cgpdfpng'

### ISSUE THREAD

**Issue by zhenchuanzhiaa** [plastex/plastex#290]
![image](https://user-images.githubusercontent.com/37968625/173381460-138b407b-e5f7-418c-892d-b6f8a5f89bd1.png)how can I solve this problem ? This problem happen when plastex demo.tex

**Comment by PatrickMassot** [comment]
I need more information to really help you. I need to see a minimal tex file triggering this issue, the full plastex output (copypasted, not as an image) and information about your system. 

That `cgpdfpng` is tried as the last imager when everything else fails, so it looks like you're trying to use an imager without having installed any usable imager. There should be a nicer error message, but things won't work anyway if you don't install anything.

**Comment by PatrickMassot** [comment]
You should get a better error handling since f2f2f6288f3172a6910fb34fe25d1a66775ea1b1.
