### ISSUE TITLE
Can you tag a new release?

### ISSUE THREAD

**Issue by christianp** [plastex/plastex#292]
I'm trying to upgrade [Chirun](https://github.com/chirun-ncl/chirun) to use Jinja2 3.1. It's currently pinned to the latest tagged release of PlasTeX, which is from 2019.

It looks like the master branch has been updated to work with Jinja2 3.0, removing `contextfilter`, but in order to use it I'll have to specify installing PlasTeX from git rather than PyPI.

So do you plan on tagging a new version any time soon?

**Comment by PatrickMassot** [comment]
I just released a new version. I'm sorry about the huge delay.

**Comment by christianp** [comment]
Thank you very much, @PatrickMassot!
