### ISSUE TITLE
\input{filename} failed to find filename.tex when kpsewhich not installed

### ISSUE THREAD

**Issue by utensil** [plastex/plastex#295]
## Description

For a main.tex looks like

```
\input{meta.tex}
\input{content}
```

plastex will find meta.tex but fail to find content.tex if kpsewhich is not installed:

```
.......... ( ./meta.tex ).......
WARNING: Could not find any file named: content
 )............
```

(for full log, see [this Github Action log](https://github.com/pygae/lean-ga/runs/7861323502?check_suite_focus=true), step "Build blueprint")

## Expected behavior

For `\input{filename}`, plastex should be able to find `filename.tex` even when `kpsewhich` is not installed.

`kpsewhich` is distributed as part of a TeX distribution such as TeXLive, so this issue means plastex has a hard dependency on a TeX distribution if we want to write `\input{filename}`, omitting `.tex`.

A full TeX distribution is not always installed, especially for a CI run only meaning to use plastex to generate some HTML. (In my case, I used [Tectonic](https://tectonic-typesetting.github.io/en-US/) for LaTeX compilation, which is just one binary.)

## Workaround

A workaround that [works](https://github.com/pygae/lean-ga/actions/runs/2873149328), is to install minimal TeX binaries including `kpsewhich` (see https://command-not-found.com/kpsewhich).

## Suggested fix

In https://github.com/plastex/plastex/blob/master/plasTeX/TeX.py#L1339-L1365 , function `kpsewhich` will first try to use `kpsewhich` to find the input file, if this fails, an exception will be thrown and a fallback will try to find the input file by literally search the filename (which, in our case, is without `.tex`) in `TEXINPUTS` paths, but there's only a file with `.tex` so the search will fail.

The suggested fix is to modify this fallback, to take into account file extensions could be omitted. But since function `kpsewhich` is used to search for other files (e.g. graphics and .bbl files), I don't know if a naive fix only considering `.tex` will be acceptable.

**Comment by PatrickMassot** [comment]
Fixed in 89508df1bb48a148dcebfb352c779a2319d993df. The fix cannot be in the function you suggested since the relevant extension to try to add depend on the command calling this function.
