### ISSUE TITLE
Mention documentation more prominently on the github page

### ISSUE THREAD

**Issue by grunweg** [plastex/plastex#302]
See [this PR](#301) for broader context.

When reading the [github page](https://plastex.github.io/plastex/), the link to the documentation doesn't jump out at me at all.
I see the link to the github repository and the source tarballs prominently. The link to the documentation is buried in the fifth paragraph, which I can only see after scrolling far down.

I would rather mention the documentation/user's guide prominently --- for instance, in place of the source tarballs, and refer to the tarballs further down the page (if at all).

Taking a step back, documentation and the source tarballs cater to different audiences. 
Can we offer separate steps for these different audiences? For example, add a navigation bar with different items for different groups. Say,
- "for users"/"user guide"/"documentation" or so
- contributing (with the github link)
- extending plasTeX, with a link to the [tutorial](https://plastex.github.io/plastex/tutorials/).

(I'm not quite sure how the first item should be called. You may know better.)

Thinking about it, I'm actually unsure why the tarballs are offered/who the target audience for those is.
People who want to install the latest version, but prefer to download the tarball over cloning the repository with all its history?
(In this case: I'd rather make a page "installation" which lists these options.)

**Comment by grunweg** [comment]
I've taken a stab at making the easier change (switching tarball and documentation links) locally. Since I can't find a repository matching this webpage, I'm attaching the [modified HTML file](https://github.com/plastex/plastex/files/9880672/index-modified.txt) of the index. (Extension renamed to .txt so github lets it through.)

If you point me at a repository, I'll be happy to submit a proper pull request. :-)
The text flow is a bit rough; suggestions welcome.

**Comment by PatrickMassot** [comment]
Thank you for your suggestions. Indeed the role of the zip and tar files was completely unclear. I suspect they came from an old template. I removed them, moved up the link to the main documentation and added a link to the contributor documentation.

**Comment by grunweg** [comment]
Thanks for the rapid response! These changes address what I was thinking.
