### ISSUE TITLE
__version__ string should say 3.0 but says 2.1

### ISSUE THREAD

**Issue by ghamerly** [plastex/plastex#308]
Since the release is now 3.0, it seems like the version string in the code needs updating.

The following lines seem relevant:
* https://github.com/plastex/plastex/blob/3ef343372b233454058d7e2700489e7604c8952c/plasTeX/client.py#L14
* https://github.com/plastex/plastex/blob/6182161533d6075bee033fcdcdbefd0f8b8d8997/plasTeX/__init__.py#L1

**Comment by PatrickMassot** [comment]
I'm really sorry about the inconvenience. Do you need to install from pypi or is it ok to have the fix in master?

**Comment by ghamerly** [comment]
Thank you! This is sufficient for now, I think! But it would be nice (easier) to have the fix in pypi.
