### ISSUE TITLE
does not install themes

### ISSUE THREAD

**Issue by mennucc** [plastex/plastex#338]
dear all, the latest version 
`master 7292660 Fix beamer argument handling and simplify code`
does not install, and hence does not use, themes.

Steps to reproduce

```shell
cd /tmp/temporary
git clone https://github.com/plastex/plastex.git
cd plastex/
python3 -m venv venv
source venv/bin/activate
pip3 install .
find -name 'theme*css'
``` 
You will notice that themes are not copied into the installed program.

Regards. a.

**Comment by PatrickMassot** [comment]
Thanks! This came from weird typos when switching to modern python packaging.
