### ISSUE TITLE
The URL given to \href should not have character substitutions applied

### ISSUE THREAD

**Issue by christianp** [plastex/plastex#342]
Here's a minimal TeX document that shows the problem:

```
\documentclass{article}
\usepackage{hyperref}
\begin{document}
    \href{a--file.pdf}{View file --}.

    A bit of text -- like that.
\end{document}
```

At the moment, plasTeX rewrite the URL `a--file.pdf` to `a–file.pdf`, as part of the normalization process.

I can't see a way of opting out of normalization for macro arguments. There's a `NoCharSubEnvironment` class, but nothing for arguments.

It looks like [`TeX.readArgumentAndSource`](https://github.com/plastex/plastex/blob/master/plasTeX/TeX.py#L765) might need to look at the `type` when deciding whether to pass charsubs to `normalize`.

**Comment by PatrickMassot** [comment]
Thanks. This issue was lying pretty deep and required quite a few modifications, but I think it is now ok. Could you confirm that it now works for you?

**Comment by christianp** [comment]
Yep, that looks like it's fixed it, thanks!
