### ISSUE TITLE
Remove Navigational Buttons

### ISSUE THREAD

**Issue by Spamakin** [plastex/plastex#352]
I'm attempting to use plasTeX as a way to make a blog. For a blog, the traditional navigational buttons built into plasTeX do not make sense. Is there a way to remove them?

**Comment by PatrickMassot** [comment]
You should use a non-default theme. If you use the standard client (ie. run the plastex command in your command line) then this is done using the `--theme=` option. The themes that ship with the HTML5 renderers can be found at https://github.com/plastex/plastex/tree/master/plasTeX/Renderers/HTML5/Themes. In particular the fragment theme outputs code without is meant to be embeddable  into a web page. But to be honest I never tested this.

**Comment by Spamakin** [comment]
I think I got it working (but I don't fully understand the template vs theme directory structure, especially including my own of one or the other)

**Comment by PatrickMassot** [comment]
I can't reproduce this issue. Do you see it on plasTeX master? Could you paste a full file you are trying to compile (putting as little as possible in it) and the way you try to compile it?

**Comment by Spamakin** [comment]
Never mind, not sure what changed but it is working now. Maybe I'll dig into why it wasn't working some other day. I think this issue can be closed
