### ISSUE TITLE
wrong catcode for @?

### ISSUE THREAD

**Issue by uhoreg** [plastex/plastex#36]
"@" is currently put in the "letter" category instead of "other".  For example, the following files don't compile properly under plasTeX, even though they do compile under LaTeX:

``` latex
\documentclass{article}
\newcommand{\foo}[1]{#1}
\begin{document}
\foo@
\end{document}
```

and

``` latex
\documentclass{article}
\begin{document}
\verb@abc@
\end{document}
```

Is there a reason that @ is in the "letter" category instead of "other" by default?

**Comment by uhoreg** [comment]
Answering my own question, changing @ to "other" instead of "letter" breaks some packages, but changing the `invoke` method from `plasTeX.Base.LaTeX.Packages.usepackage` to temporarily change @ to letter before the `for file ...` loop, and changing it back after the loop solves this.  i.e.

```python
        at_catcode = self.ownerDocument.context.whichCode('@')
        self.ownerDocument.context.catcode('@', Token.CC_LETTER)
        for file in a['names']:
            self.load(tex, file, a['options'])
        self.ownerDocument.context.catcode('@', at_catcode)
```

**Comment by PatrickMassot** [comment]
Fixed, thanks!
