### ISSUE TITLE
Parser incorrectly groups $$ as a single closing element for $

### ISSUE THREAD

**Issue by uhoreg** [plastex/plastex#37]
Hmm.  It looks like my corpus hits some strange edge cases.  The latest one that I've run across is that if you have two math chunks with no space between them (e.g. `$x$$y$`), then the parser, as far as I can tell, seems to think that the `$$` in the middle is a single closing tag for the math.  Most of the time it seems to end up with something somewhat reasonable, but the issue can be seen more clearly with this document:

``` latex
\documentclass{article}

\begin{document}
\begin{tabular}{cc}
& $ $$ x $ \\
& $ $$ \sin $
\end{tabular}
\end{document}
```

Running that document through plasTeX, it complains about: `WARNING: Using default renderer for sin`.

**Comment by kesmit13** [comment]
I'm not sure this one is fixable in a reasonable way.  plasTeX isn't quite as good as LaTeX in parsing, and it gets confused sometimes.  At the moment, I can't think of a good way to solve this one because I'm not sure there's enough context to know how to handle it.

**Comment by PatrickMassot** [comment]
@kesmit13 I don't think trying to parse an horror like ``$ $$ x $`` is worth investing part of your limited plasTeX development time.

**Comment by PatrickMassot** [comment]
It seems fair to say this won't be fixed (but anyone wanting to fix it can still reopen this issue).
