### ISSUE TITLE
Formatting identifiers

### ISSUE THREAD

**Issue by kskyten** [plastex/plastex#51]
I'm trying to modify the `id` of a node so that it is a proper identifier for a `xml:id` attribute. Specifically the ids can't contain spaces or dots which is pretty common in latex labels. I tried to do modify the id of the node in the `digest` method of the node but it didn't seem to work.
```python
class section(Command):
    args = 'title:str'
    def digest(self, tokens):
        res = Command.digest(self, tokens)
        self.id = make_valid_id(res.id)

        return res
```
The end result I'm after is converting
```
\section{Simulation of Discrete Probabilities} \label{sec 1.1}
```
into
```
<section xml:id="sec-1_1"> 
```

**Comment by PatrickMassot** [comment]
In this specific example (section command), you are inheriting from the wrong class and ``res.id`` is not what you want to use. Try:
```python
class mysection(StartSection):
    level = Command.SECTION_LEVEL
    counter = 'section'

    def digest(self, tokens):
        res = Command.digest(self, tokens)
        self.id = make_valid_id(self.id)

        return res
```

where ``StartSection`` comes from ``plasTeX/Base/LaTeX/Sectioning.py``.

**Comment by PatrickMassot** [comment]
This has been waiting for more question almost three years, so I close it.
