### ISSUE TITLE
Status of DocBook Renderer

### ISSUE THREAD

**Issue by PatrickMassot** [plastex/plastex#61]
In the documentation, there is a section on DocBook Renderer containing only the sentence "Not yet implemented'. But there is a DocBook Renderer in the codebase. Is it a stub or is it usable? I don't know anything about DocBook so I cannot test this renderer but it would be nice to document it, if it is usable.

**Comment by PatrickMassot** [comment]
@tiarno would you have time to write a couple of sentences about this? I've tried again to use the DocBook renderer, but cannot render any TeX file. Do you have any example that compiles using the plastex command? Or is it usable only with plasTeX used as a library?

**Comment by tiarno** [comment]
Hi Patrick, I have never used the plastex command to create DocBook documents, but always used plastex as a library. This is the pattern I use at work. Assumes `fname` is the name of the LaTeX source document and that TEXINPUTS and DocBookRENDERER env vars are set. This will render the xml file in the current directory. 

    from plasTeX.ConfigManager import ConfigManager
    from plasTeX.TeX import TeX
    from plasTeX.Renderers.DocBook import Renderer
    from plasTeX import TeXDocument

    texdocument = TeXDocument(config= ConfigManager())
    tex = TeX(texdocument, myfile=fname)
    tex.parse()
    r = Renderer()
    r.render(texdocument)

**Comment by PatrickMassot** [comment]
Fixed in 4d4dd32.
