### ISSUE TITLE
Commands like \bf do not change text style beyond section ending

### ISSUE THREAD

**Issue by gab50000** [plastex/plastex#82]
If I have a tex file like this one:

```
\documentclass{article}
\begin{document}
  \section{Section 1}
     Molestiae rerum consequatur fugit qui. Ipsa ex nihil earum quibusdam. \bf Est eos quasi cupiditate. 
  \section{Section 2}
     Fuga repellendus provident explicabo nulla deleniti ut. Delectus ipsam cupiditate hic. Quia officiis ut maiores nesciunt porro.
\end{document}
```

the Latex result will have a bold text from "Est eos" until the end of the document.
PlasTeX, however,  will only print bold text until the end of the first section.
Is it possible to change this behavior? 
(Background is, as in my previous post, that I am currently trying to convert a large Latex project written by several people over many years, where things like this may occur in some parts of the text.)

I would probably have to overwrite the digest method of the relevant commands, right?

**Comment by kesmit13** [comment]
This is very unlikely to change.  TeX is a presentation language so it can just flip style attributes on and off throughout a document.  plasTeX creates a document object where commands are scoped within the section that they are in.  So nested styles will always be terminated by their enclosing section.  Trying to resolve style attributes across sections breaks would be a huge endeavor.

**Comment by gab50000** [comment]
Ok, good to know. Almost thought so.
Thanks for the quick reply!

**Comment by PatrickMassot** [comment]
I think there is not much more to add to this conversation, so I'll close it.
