### ISSUE TITLE
Working directory in a gspdfpng Imager compiling latex

### ISSUE THREAD

**Issue by peterzjx** [plastex/plastex#99]
I was trying to convert a .tex file containing external pdf graphics. I coded in python and called through` if __name__ == "main"` in the terminal. The resulting converted png were sketchy placeholders (white background with a black box and black filenames in the center). However I tried the command line with` --imager=gspdfpng`, everything worked just fine.

I looked into the plastex source code and saw `Imager `calling the `compileLatex `method with its cwd being a temp directory, and pdflatex couldn't find the dependent pdf graphics, as only the images.tex file was created inside that directory. However, in the command line method, somehow pdflatex knows where to find those files. 

This situation would work if pdflatex is called inside the source directory with those graphics. But in both cases, the cwd is just a temp directory. What makes them behave differently?

**Comment by kesmit13** [comment]
It changes to a temporary directory so that the image creation process can clean up after itself.  If it ran in the current directory, it would create a mess of files that it might not be able to clean up properly.  Your issue is likely that you need to set your TEXINPUTS environment variable to include the directory where your source files are.

**Comment by peterzjx** [comment]
Thank you kesmit. I'm not sure if the default command line call would change TEXINPUTS, so how does the pdflatex know where to find the input files?
The python file for comparison is a PageTemplate Renderer, with default settings.

**Comment by kesmit13** [comment]
It simply adds the current working directory to the beginning of TEXINPUTS.

**Comment by PatrickMassot** [comment]
I think Kevin answered this question a long time ago, so let's close it.
